### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by jrpdn** [Dhruv-Acharya/Gem5ToMcPAT-Parser#3]
HI Dhruv,
I am getting a error in conversion of gem5 O/P to Mcpat XML input , the error is
Traceback (most recent call last):
  File "Gem5ToMcPAT-Parser.py", line 300, in <module>
    main()
  File "Gem5ToMcPAT-Parser.py", line 296, in main
    prepareTemplate(args.output)
  File "Gem5ToMcPAT-Parser.py", line 149, in prepareTemplate
    if config["system"]["cpu"][coreCounter]["isa"][0]["type"] == "X86ISA":
KeyError: 'isa'

I have designed a NOC-Mesh Topology 
So please see this and reply as soon as possible
Thank You

**Comment by Dhruv-Acharya** [comment]
Hey,
I'm no longer actively maintaining this, Feel free raise a PR to fix.
