### ISSUE TITLE
Gem5 to Mcpat

### ISSUE THREAD

**Issue by jrpdn** [Dhruv-Acharya/Gem5ToMcPAT-Parser#4]
Hi,
I have used the parser given by you, but it gives me the following error
Traceback (most recent call last):
  File "Gem5ToMcPAT-Parser.py", line 301, in <module>
    main()
  File "Gem5ToMcPAT-Parser.py", line 298, in main
    dumpMcpatOut(args.output)
  File "Gem5ToMcPAT-Parser.py", line 267, in dumpMcpatOut
    param.attrib['value'] = str(eval(str(value)))
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for /: 'float' and 'list'
Please can anyone help me to rectify it.

Thanks and best regards.

**Comment by Nisarg-Sheth** [comment]
This error is mostly due to your template.xml file. The stats in your template.xml file do not match the stats in your stats.txt file from gem5. Print 'value' before line 267 and check the last parameter printed. This last parameter would be the statistic your parser is looking for in stats.txt

**Comment by Dhruv-Acharya** [comment]
Hey all,
I'm no longer actively maintaining this, Feel free raise a PR to fix.
